// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAfoMzf4EarNxwELujKjxqz7CMOxsAl9E',
    appId: '1:986312694554:web:634bfbc514919f4ffdeaa3',
    messagingSenderId: '986312694554',
    projectId: 'notidemo-47adf',
    authDomain: 'notidemo-47adf.firebaseapp.com',
    storageBucket: 'notidemo-47adf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMiDJ6KnHFs4TpEB3Mg2oQcJxLmal0azE',
    appId: '1:986312694554:android:54106487f4c82ee2fdeaa3',
    messagingSenderId: '986312694554',
    projectId: 'notidemo-47adf',
    storageBucket: 'notidemo-47adf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0OwOzzovxfZk-E4X10z_vToMIX7BDKPs',
    appId: '1:986312694554:ios:359cb897dc77f21ffdeaa3',
    messagingSenderId: '986312694554',
    projectId: 'notidemo-47adf',
    storageBucket: 'notidemo-47adf.firebasestorage.app',
    iosBundleId: 'com.example.medcaremobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0OwOzzovxfZk-E4X10z_vToMIX7BDKPs',
    appId: '1:986312694554:ios:359cb897dc77f21ffdeaa3',
    messagingSenderId: '986312694554',
    projectId: 'notidemo-47adf',
    storageBucket: 'notidemo-47adf.firebasestorage.app',
    iosBundleId: 'com.example.medcaremobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAfoMzf4EarNxwELujKjxqz7CMOxsAl9E',
    appId: '1:986312694554:web:7e426c58aecef5fcfdeaa3',
    messagingSenderId: '986312694554',
    projectId: 'notidemo-47adf',
    authDomain: 'notidemo-47adf.firebaseapp.com',
    storageBucket: 'notidemo-47adf.firebasestorage.app',
  );
}
